project:
  type: book
  output-dir: docs

book:
  title: "CS5027: Fifty Discoveries, Fifty Inventions"
  author: "Kevin Fo"
  date: "10/01/2023"
  chapters:
    - index.qmd
    - part: "**PART 1: LECTURES**"
      chapters:
      - intro.qmd
      - wk2.qmd
      - wk3.qmd
  toc-depth: 3
  comments: 
    hypothesis: true 
  sharing: [facebook, twitter]
  reader-mode: true

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

